version: '3'
services:
  # MySQL Service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: D3v3l0p3r@
      MYSQL_DATABASE: votingsystem
    ports:
      - "3306:3306"
    networks:
      - voting-network

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:management"
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: dev123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - voting-network
    command: /bin/bash -c "scripts/rabbitmq-init.sh && rabbitmq-server"

  # Spring Boot Application
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/votingsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: D3v3l0p3r@
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_JACKSON_DESERIALIZATION_FAIL_ON_UNKNOWN_PROPERTIES: "true"
      VOTING_RESULT_RABBITMQ_QUEUE: voting.result
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: developer
      SPRING_RABBITMQ_PASSWORD: dev123
      VOTING_RESULT_RABBITMQ_EXCHANGE: voting.exchange
      VOTING_RESULT_RABBITMQ_ROUTING_KEY: routing-key
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge
